### ISSUE TITLE
Include customization help on README file

### ISSUE THREAD

**Issue by dyorgio** [basakpie/vaadin-onoffswitch-addon#1]
First of all, congratulations, it is an amazing add-on.

I want to customize the colors used by it, what is the better way to do it?

**Comment by dyorgio** [comment]
Found it!
```css
.onoffswitch-slider.on {
    background-color: $your_color;
    border-color: $your_color;
}
.onoffswitch-slider.on:before {  
    border-color: $your_color;
}
```
